config/routes.rb
Rails.application.routes.draw do
  get 'proyects/index'
  get 'proyects/new', to: "proyects#new"
  post 'proyects', to: "proyects#create"
  get 'posts/index'
  post 'post/create', to: "posts#create", as: "post_create"
  root "proyects#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
    validates :image, presence: true
    # before_save :ban_word


    # def ban_word
    #     self.content.gsub!("spolier" , "")
    # end
end

app/models/proyect.rb
class Proyect < ApplicationRecord
    enum state:[:propuesta, :en_progreso, :terminado]
    validates :name, :description, :state, :initial_date, :finish_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def create
    @post = Post.create(
      title: params['title'],
      content: params['content'], 
      image: params['image']
    )
    @post.content.gsub!("spoiler", "")
    if @post.save
      redirect_to root_path
    end
  end
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  def index
    if params[:state].present?
      @proyects = Proyect.where('state = ?', params[:state])
    else
      @proyects = Proyect.all
    end
  end
  
  def new
    @proyect = Proyect.new
  end
  
  def create
    @proyect= Proyect.create(proyect_params)
    if @proyect.save
      redirect_to root_path, notice: "se ha creado el proyecto"
    else
      redirect_to root_path, alert: "No se guardo el proyecto"
    end
  end
  
  private

  def proyect_params
    params.require(:proyect).permit(:name, :description, :state, :initial_date, :finish_date)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1> TODOS LOS POST </h1>

<%= form_with(url: post_create_path, model: @post, local: true ) do |f| %>
    <%= f.label :titulo %>
    <%= f.text_field :title %>

    <%= f.label :imagen %>
    <%= f.text_field :image %>

    <%= f.label :contenido %>
    <%= f.text_field :content %>

    <%= f.submit "CREAR POST"%>
<% end %>



<% @posts.each do |post| %>
    <div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <%= image_tag post.image, class: "img-fluid" %>
        </div>
        <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title"><%= post.title %></h5>
            <p class="card-text"><%= post.content %></p>
            <p class="card-text"><small class="text-muted"><%= post.created_at %></small></p>
        </div>
        </div>
    </div>
    </div>
<% end %>


    

    

app/views/proyects/create.html.erb
<h1>Proyects#create</h1>
<p>Find me in app/views/proyects/create.html.erb</p>

app/views/proyects/index.html.erb
<h1>Proyects#index</h1>
<p>Find me in app/views/proyects/index.html.erb</p>

<form> 
    Buscar proyecto por estado:
    <div class="col-md-3 mb-3">
      <label for="validationDefault04">State</label>
      <select class="custom-select" name="state">
        <option value= "0" >propuesta</option>
        <option value= "1" >En Progreso</option>
        <option value= "2 ">Termiando</option>
        <option value= "">todo</option>
      </select>
    </div>
  <button class="btn btn-primary" type="submit">Buscar proyecto</button>
</form>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Estado</th>
      <th scope="col">Fecha inicio</th>
      <th scope="col">Fecha termino</th>
    </tr>
  </thead>
  <tbody>
    <% @proyects.each do |proyect| %>
    <tr>
        <td><%= proyect.id%></td>
        <td><%= proyect.name%></td>
        <td><%= proyect.description%></td>
        <td><%= proyect.state%></td>
        <td><%= proyect.initial_date%></td>
        <td><%= proyect.finish_date%></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "nuevo post", proyects_new_path, class: "btn btn-info" %>

app/views/proyects/new.html.erb
<%= form_with(model: @proyect, local: true) do |f| %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description %>
    </div>
    <div class="form-group">
        <%= f.label :state %>
        <%= f.select :state, options_for_select(Proyect.states.keys) %>
    </div>
    <div class="form-group">
        <%= f.label :initial_date %>
        <%= f.date_field :initial_date %>
    </div>
    <div class="form-group">
        <%= f.label :finish_date %>
        <%= f.date_field :finish_date %>
    </div>

    <%= f.submit "crear proyecto", class: "btn btn-success"%>
<% end %>